/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'id' : string,
  'status' : string,
  'date' : string,
  'note' : string,
  'checkInTime' : bigint,
  'employeeId' : string,
}
export interface Employee {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'employeeId' : string,
  'faceDescriptor' : string,
  'photo' : ExternalBlob,
  'department' : string,
  'dailySalary' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Holiday {
  'id' : bigint,
  'date' : string,
  'createdAt' : bigint,
  'reason' : string,
}
export interface SalaryPayment {
  'id' : bigint,
  'note' : string,
  'createdAt' : bigint,
  'paidDate' : string,
  'employeeId' : string,
  'amount' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAttendanceRecord' : ActorMethod<
    [string, string, string, bigint, string],
    string
  >,
  'addHoliday' : ActorMethod<[string, string], bigint>,
  'addSalaryPayment' : ActorMethod<[string, bigint, string, string], bigint>,
  'deleteAttendanceRecord' : ActorMethod<[string], undefined>,
  'deleteEmployee' : ActorMethod<[string], undefined>,
  'deleteHoliday' : ActorMethod<[bigint], undefined>,
  'deleteSalaryPayment' : ActorMethod<[bigint], undefined>,
  'getAllAttendanceRecords' : ActorMethod<[], Array<AttendanceRecord>>,
  'getAllSalaryPayments' : ActorMethod<[], Array<SalaryPayment>>,
  'getAttendanceByDate' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getAttendanceByEmployeeId' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getEmployeeByEmployeeId' : ActorMethod<[string], [] | [Employee]>,
  'getSalaryPaymentsByEmployee' : ActorMethod<[string], Array<SalaryPayment>>,
  'listAllEmployees' : ActorMethod<[], Array<Employee>>,
  'listHolidays' : ActorMethod<[], Array<Holiday>>,
  'registerEmployee' : ActorMethod<
    [string, string, string, bigint, string, ExternalBlob],
    string
  >,
  'updateEmployee' : ActorMethod<
    [string, string, string, bigint, string, ExternalBlob],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];