/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'id' : string,
  'status' : string,
  'employeeName' : string,
  'checkInTime' : bigint,
  'employeeId' : string,
  'photo' : ExternalBlob,
  'department' : string,
}
export interface Employee {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'photo' : ExternalBlob,
  'department' : string,
}
export type ExternalBlob = Uint8Array;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAttendanceRecord' : ActorMethod<
    [string, string, string, bigint, ExternalBlob, string],
    string
  >,
  'deleteAttendanceRecord' : ActorMethod<[string], undefined>,
  'deleteEmployee' : ActorMethod<[string], undefined>,
  'getAllAttendanceRecords' : ActorMethod<[], Array<AttendanceRecord>>,
  'getAttendanceByDate' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getDailySummary' : ActorMethod<
    [string],
    {
      'presentCount' : bigint,
      'absentEmployees' : Array<string>,
      'lateCount' : bigint,
    }
  >,
  'listAllEmployees' : ActorMethod<[], Array<Employee>>,
  'listEmployeesByDepartment' : ActorMethod<[], Array<Employee>>,
  'registerEmployee' : ActorMethod<[string, string, ExternalBlob], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];