/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'date' : IDL.Text,
  'note' : IDL.Text,
  'checkInTime' : IDL.Int,
  'employeeId' : IDL.Text,
});
export const SalaryPayment = IDL.Record({
  'id' : IDL.Nat,
  'note' : IDL.Text,
  'createdAt' : IDL.Int,
  'paidDate' : IDL.Text,
  'employeeId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Employee = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'employeeId' : IDL.Text,
  'faceDescriptor' : IDL.Text,
  'photo' : ExternalBlob,
  'department' : IDL.Text,
  'dailySalary' : IDL.Nat,
});
export const Holiday = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAttendanceRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addHoliday' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addSalaryPayment' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteAttendanceRecord' : IDL.Func([IDL.Text], [], []),
  'deleteEmployee' : IDL.Func([IDL.Text], [], []),
  'deleteHoliday' : IDL.Func([IDL.Nat], [], []),
  'deleteSalaryPayment' : IDL.Func([IDL.Nat], [], []),
  'getAllAttendanceRecords' : IDL.Func(
      [],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAllSalaryPayments' : IDL.Func([], [IDL.Vec(SalaryPayment)], ['query']),
  'getAttendanceByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByEmployeeId' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getEmployeeByEmployeeId' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(Employee)],
      ['query'],
    ),
  'getSalaryPaymentsByEmployee' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SalaryPayment)],
      ['query'],
    ),
  'listAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'listHolidays' : IDL.Func([], [IDL.Vec(Holiday)], ['query']),
  'registerEmployee' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, ExternalBlob],
      [IDL.Text],
      [],
    ),
  'updateEmployee' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, ExternalBlob],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'date' : IDL.Text,
    'note' : IDL.Text,
    'checkInTime' : IDL.Int,
    'employeeId' : IDL.Text,
  });
  const SalaryPayment = IDL.Record({
    'id' : IDL.Nat,
    'note' : IDL.Text,
    'createdAt' : IDL.Int,
    'paidDate' : IDL.Text,
    'employeeId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Employee = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'employeeId' : IDL.Text,
    'faceDescriptor' : IDL.Text,
    'photo' : ExternalBlob,
    'department' : IDL.Text,
    'dailySalary' : IDL.Nat,
  });
  const Holiday = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAttendanceRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addHoliday' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addSalaryPayment' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteAttendanceRecord' : IDL.Func([IDL.Text], [], []),
    'deleteEmployee' : IDL.Func([IDL.Text], [], []),
    'deleteHoliday' : IDL.Func([IDL.Nat], [], []),
    'deleteSalaryPayment' : IDL.Func([IDL.Nat], [], []),
    'getAllAttendanceRecords' : IDL.Func(
        [],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAllSalaryPayments' : IDL.Func([], [IDL.Vec(SalaryPayment)], ['query']),
    'getAttendanceByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByEmployeeId' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getEmployeeByEmployeeId' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(Employee)],
        ['query'],
      ),
    'getSalaryPaymentsByEmployee' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SalaryPayment)],
        ['query'],
      ),
    'listAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'listHolidays' : IDL.Func([], [IDL.Vec(Holiday)], ['query']),
    'registerEmployee' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, ExternalBlob],
        [IDL.Text],
        [],
      ),
    'updateEmployee' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, ExternalBlob],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };