/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'employeeName' : IDL.Text,
  'checkInTime' : IDL.Int,
  'employeeId' : IDL.Text,
  'photo' : ExternalBlob,
  'department' : IDL.Text,
});
export const Employee = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'photo' : ExternalBlob,
  'department' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAttendanceRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int, ExternalBlob, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteAttendanceRecord' : IDL.Func([IDL.Text], [], []),
  'deleteEmployee' : IDL.Func([IDL.Text], [], []),
  'getAllAttendanceRecords' : IDL.Func(
      [],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getDailySummary' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'presentCount' : IDL.Nat,
          'absentEmployees' : IDL.Vec(IDL.Text),
          'lateCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'listAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'listEmployeesByDepartment' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'registerEmployee' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'employeeName' : IDL.Text,
    'checkInTime' : IDL.Int,
    'employeeId' : IDL.Text,
    'photo' : ExternalBlob,
    'department' : IDL.Text,
  });
  const Employee = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'photo' : ExternalBlob,
    'department' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAttendanceRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int, ExternalBlob, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteAttendanceRecord' : IDL.Func([IDL.Text], [], []),
    'deleteEmployee' : IDL.Func([IDL.Text], [], []),
    'getAllAttendanceRecords' : IDL.Func(
        [],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getDailySummary' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'presentCount' : IDL.Nat,
            'absentEmployees' : IDL.Vec(IDL.Text),
            'lateCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'listAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'listEmployeesByDepartment' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'registerEmployee' : IDL.Func(
        [IDL.Text, IDL.Text, ExternalBlob],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };